version: '3.7'

services:
  app_server:
    image: shopware/development:latest
    links:
      - app_mysql:mysql
      - mailhog:mailhog
    extra_hosts:
      - "docker.vm:127.0.0.1"
    volumes:
      - ~/.composer:/.composer
    tmpfs:
      - /tmp:mode=1777

  app_mysql:
    build: dev-ops/docker/containers/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app

  cypress:
    image: cypress/included:3.8.1
    tty: true
    ipc: host
    links:
      - app_server:docker.vm
    environment:
      - CYPRESS_baseUrl=http://docker.vm:8000
      - DISPLAY
    volumes:
      - ./vendor/shopware/platform/src/Storefront/Resources/app/storefront/test/e2e:/e2e-Storefront
      - ./vendor/shopware/platform/src/Administration/Resources/app/administration/test/e2e:/e2e-Administration
      # for Cypress to communicate with the X11 server pass this socket file
      # in addition to any other mapped volumes
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: /bin/bash

  mailhog:
    image: mailhog/mailhog

  adminer:
    image: adminer:latest
    links:
      - app_mysql:mysql

  elasticsearch:
    image: elastic/elasticsearch:7.1.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
